#!/bin/sh

case $1 in
    -m)
        echo "x86_64"
        ;;
    -p)
        echo "x86_64"
        ;;
    -r)
        echo $(find /lib/modules -maxdepth 1 -type d| awk -F'/' '{print $4}')
        ;;
    -s)
        echo "Linux"
        ;;
    -v)
        echo "#50-Ubuntu SMP Sat Nov 1 02:47:06 CET 2014"
        ;;
esac
## vim: set sw=4 sts=4 et foldmethod=syntax : ##
